version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    network_mode: bridge
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'
  
  app:
    container_name: airbnb-app
    restart: always
    build: .
    ports:
      - '8080:8080'
    environment:
        APP_PORT: '8080'
        MONGO_URI: mongodb://mongo:27017
        NODE_ENV: prod

    network_mode: bridge
    depends_on:
      - mongo
    links:
      - mongo

volumes: 
  mongo: {}